### ISSUE TITLE
Issue with isoPlot function in isomiRs package

### ISSUE THREAD

**Issue by palbioinfor** [lpantano/seqbuster#22]
Hi,
I am using isomiRs package for my isomirs analysis project. I have successfully run it but when I re-ran the whole program with same data I am getting different plots as output of 'isoPlot' function which plots isomirs abundance and I get different plot every time I run it with same data. Does anyone have idea why this is happening? Also Is there any alternative way to produce this plot, in case this is not fixable?

**Comment by lpantano** [comment]
Hi,

Is there any way you can save the variable where you have the object with save(obj, file=“path/object.rda”) and share it with me. 

As well, can you tell me what is the variability you are seeing? All these plots use the jitter option to spread the dots on the x-axis, that is random, but that spread doesn’t mean anything. It is just to avoid overlap of points. The useful information is the y-axis and the size of the dot. Is that what you refer as different figures?

It would be good to have 2-3 examples where you see the difference.

Cheers

**Comment by palbioinfor** [comment]
Hi,
Thanks a lot for your response and sorry for being late in replying you. 

I am attaching two pictures here which are iso5 distribution with same data . I just executed the 'isoPlot' command twice with same data.

![screen shot 2018-06-22 at 11 45 36 am](https://user-images.githubusercontent.com/36253759/41785976-3577bef4-7612-11e8-9b4e-83ac7baae4c4.png)

![screen shot 2018-06-22 at 11 45 59 am](https://user-images.githubusercontent.com/36253759/41785987-406ab668-7612-11e8-9d32-d7965665c866.png)

**Comment by lpantano** [comment]
Hi,

I see.

Yes, the difference are due to the random values in the x-axis, this is to avoid overlap of points. What it is important is the y-axis what is constant, for instance, 4 red top points and 2 blue top points at  -1 are the same.

Hope this help, I can try to change the way the plot is as well to avoid this  issue in the future.

Cheers

**Comment by palbioinfor** [comment]
Okay. Thanks.


Also , I had few other queries as well. I want to have a table of percentage and counts of miRNAs and their isomirs (all kinds; iso3,iso5 ,add and subs) and I want to plot this data. How can I do that? 

Plus some other queries-

1.  I accessed metadata but some fields are unclear to me like in raw data-
 
mir_f ,  mir_n ,  mism_n , mism_f , enrich , af , bias , score

2.  isoList output of sample 1 of 'iso3' gives an output like-

![screen shot 2018-06-22 at 3 34 56 pm](https://user-images.githubusercontent.com/36253759/41795841-37fcf2d2-7632-11e8-8233-85a6481209c7.png)

What does 'size' mean here (and negative value?) and again since as ID, merged miRNA name is used how would I know which one is isomiR here and what kind?  I need to  get data of counts and percentage of let's say top 20 diff expressed miRNAs and their isomirs?

3. Is there any way to have metadata for all the samples together?


Thanks for the earlier responses. You are being a great help to me.

**Comment by lpantano** [comment]
Hi,

sorry for the delay, I have been away the last week.

Question 1 need a little bit of time to answer and I’ll do it by updating the documentation so other people can read it as well.

For question two is the number of nts that are involved in the variant and the sign indicate if the nt is removed from the mature sequences or added.

For the last question, the only way it would be to do a bind row/columns. However the new version of isomiRs should have something similar to that because I change the structure of the object, maybe you want to give it a try.


Thanks for the questions it helps me to improve docs!

**Comment by lpantano** [comment]
Hi,

just chiming in here, I reduced a lot the object information so there are no so many table around where there could be confusion for the users:

now the object contain only the rawdata in the metadata slot as explained here: 

http://lpantano.github.io/isomiRs/reference/IsomirDataSeq.html

```
metadata contains one list:

rawData is a data.frame with the information of each sequence found in the data and the counts for each sample.

```

thanks for the comments.
